import { Source } from "@/lib/db/types";

export const DEFAULT_SOURCES: Source[] = [
  // Tier 1: AI & Computing Research Labs
  {
    id: "openai-blog",
    name: "OpenAI Research & News",
    type: "lab",
    url: "https://openai.com/news",
    rssUrl: "https://openai.com/news/rss.xml",
    trustLevel: "TIER_1_LAB",
    category: "LLMs",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    type: "lab",
    url: "https://deepmind.google/blog",
    rssUrl: "https://deepmind.google/blog/rss.xml",
    trustLevel: "TIER_1_LAB",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    type: "lab",
    url: "https://huggingface.co/blog",
    rssUrl: "https://huggingface.co/blog/feed.xml",
    trustLevel: "TIER_1_LAB",
    category: "OPEN SOURCE",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "mit-ai-news",
    name: "MIT News: Computing & AI",
    type: "lab",
    url: "https://news.mit.edu/topic/artificial-intelligence2",
    rssUrl: "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml",
    trustLevel: "TIER_1_LAB",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "bair-blog",
    name: "Berkeley AI Research (BAIR)",
    type: "lab",
    url: "https://bair.berkeley.edu/blog",
    rssUrl: "https://bair.berkeley.edu/blog/feed.xml",
    trustLevel: "TIER_1_LAB",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "microsoft-research",
    name: "Microsoft Research",
    type: "lab",
    url: "https://www.microsoft.com/en-us/research/blog",
    rssUrl: "https://www.microsoft.com/en-us/research/feed/",
    trustLevel: "TIER_1_LAB",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },

  // Tier 1: Premier Engineering Blogs (Systems, Architecture, Software Engineering)
  {
    id: "netflix-techblog",
    name: "Netflix TechBlog",
    type: "rss",
    url: "https://netflixtechblog.com",
    rssUrl: "https://netflixtechblog.com/feed",
    trustLevel: "TIER_1_LAB",
    category: "SYSTEMS",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "uber-engineering",
    name: "Uber Engineering",
    type: "rss",
    url: "https://www.uber.com/blog/engineering",
    rssUrl: "https://www.uber.com/blog/engineering/rss/",
    trustLevel: "TIER_1_LAB",
    category: "SOFTWARE ENGINEERING",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "github-blog",
    name: "The GitHub Blog: Engineering",
    type: "rss",
    url: "https://github.blog/category/engineering/",
    rssUrl: "https://github.blog/category/engineering/feed/",
    trustLevel: "TIER_1_LAB",
    category: "SOFTWARE ENGINEERING",
    enabled: true,
    errorCount: 0,
  },

  // Tier 1: Academic Repositories (Broad Computer Science)
  {
    id: "arxiv-cs-se",
    name: "arXiv cs.SE (Software Engineering)",
    type: "arxiv",
    url: "https://arxiv.org/list/cs.SE/recent",
    trustLevel: "TIER_1_ACADEMIC",
    category: "SOFTWARE ENGINEERING",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "arxiv-cs-dc",
    name: "arXiv cs.DC (Distributed & Cloud Computing)",
    type: "arxiv",
    url: "https://arxiv.org/list/cs.DC/recent",
    trustLevel: "TIER_1_ACADEMIC",
    category: "DISTRIBUTED SYSTEMS",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "arxiv-cs-db",
    name: "arXiv cs.DB (Databases)",
    type: "arxiv",
    url: "https://arxiv.org/list/cs.DB/recent",
    trustLevel: "TIER_1_ACADEMIC",
    category: "DATABASES",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "arxiv-cs-cr",
    name: "arXiv cs.CR (Cryptography & Security)",
    type: "arxiv",
    url: "https://arxiv.org/list/cs.CR/recent",
    trustLevel: "TIER_1_ACADEMIC",
    category: "SECURITY",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI (Artificial Intelligence)",
    type: "arxiv",
    url: "https://arxiv.org/list/cs.AI/recent",
    trustLevel: "TIER_1_ACADEMIC",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "arxiv-cs-lg",
    name: "arXiv cs.LG (Machine Learning)",
    type: "arxiv",
    url: "https://arxiv.org/list/cs.LG/recent",
    trustLevel: "TIER_1_ACADEMIC",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "openalex-cs",
    name: "OpenAlex Works Graph",
    type: "arxiv",
    url: "https://openalex.org",
    trustLevel: "TIER_1_ACADEMIC",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "semanticscholar-cs",
    name: "Semantic Scholar Graph",
    type: "arxiv",
    url: "https://www.semanticscholar.org",
    trustLevel: "TIER_1_ACADEMIC",
    category: "RESEARCH",
    enabled: true,
    errorCount: 0,
  },

  // Tier 2: Verified Technical Press
  {
    id: "techcrunch-ai",
    name: "TechCrunch Enterprise & AI",
    type: "rss",
    url: "https://techcrunch.com/category/artificial-intelligence/",
    rssUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    trustLevel: "TIER_2_TECH_PRESS",
    category: "INDUSTRY",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "ars-technica",
    name: "Ars Technica: Information Technology",
    type: "rss",
    url: "https://arstechnica.com/information-technology/",
    rssUrl: "https://arstechnica.com/information-technology/feed/",
    trustLevel: "TIER_2_TECH_PRESS",
    category: "SYSTEMS",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "the-verge-tech",
    name: "The Verge Tech",
    type: "rss",
    url: "https://www.theverge.com/tech",
    rssUrl: "https://www.theverge.com/rss/index.xml",
    trustLevel: "TIER_2_TECH_PRESS",
    category: "PRODUCT",
    enabled: true,
    errorCount: 0,
  },
  {
    id: "newsapi-tech",
    name: "NewsAPI Technology Headlines",
    type: "rss",
    url: "https://newsapi.org",
    trustLevel: "TIER_2_TECH_PRESS",
    category: "INDUSTRY",
    enabled: true,
    errorCount: 0,
  },

  // Tier 3: Technical Community
  {
    id: "hackernews-frontpage",
    name: "Hacker News Technical Stories",
    type: "hackernews",
    url: "https://news.ycombinator.com",
    trustLevel: "TIER_3_COMMUNITY",
    category: "COMMUNITY",
    enabled: true,
    errorCount: 0,
  },
];
